//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelPractice.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HotelMaster
    {
        public int HotelId { get; set; }
        public string HotelName { get; set; }
        public string HtlTel { get; set; }
        public string HtlAddress { get; set; }
        public string HtlPic { get; set; }
        public byte[] HtlByteImage { get; set; }


        //[DisplayName("飯店id")]
        //public int HotelId { get; set; }
        //[DisplayName("飯店名稱")]
        //public string HotelName { get; set; }
        //[DisplayName("電話")]
        //public string HtlTel { get; set; }
        //[DisplayName("地址")]
        //public string HtlAddress { get; set; }
        //[DisplayName("圖片")]
        //public string HtlPic { get; set; }
        //[DisplayName("圖片")]
        //public byte[] HtlByteImage { get; set; }
    }
}
